---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 3000, host: 3000 }]
    - ["private_network", { ip: "192.168.33.10" }]

provisioner:
  name: policyfile_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    attributes:
